excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://puellanutellae.github.io
title: Puella Nutellae blog
tagline: A log of everyday life
description: My awesome new site
paginate: 5